name: G2PT_github_unit_test
channels:
  - pytorch-nightly
  - biobuilds
  - plotly
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - aiohappyeyeballs=2.4.0=py38h06a4308_0
  - aiohttp=3.10.5=py38h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - almosthere=2.0.2=h46c0cb4_1
  - anyio=4.2.0=py38h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - asciitree=0.3.3=py_2
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.3=py38h06a4308_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py38h06a4308_0
  - bed-reader=1.0.0=py38hc45e7f3_0
  - bgen=4.1.3=ha0ad84f_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.3=h6a678d5_0
  - bokeh=2.4.3=py38h06a4308_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py38ha9d4c09_0
  - brotli=1.0.9=h5eee18b_9
  - brotli-bin=1.0.9=h5eee18b_9
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - cbgen=1.0.1=py38h497a2fe_1
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.17.1=py38h1fdaa30_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py38h06a4308_0
  - cloudpickle=3.0.0=py38h06a4308_0
  - colorama=0.4.6=py38h06a4308_0
  - comm=0.2.1=py38h06a4308_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.4=hbda6634_3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.2=py38h5eee18b_0
  - dash-renderer=0.20.0=py_0
  - dask=2023.4.1=py38h06a4308_1
  - dask-core=2023.4.1=py38h06a4308_0
  - dask-glm=0.2.0=py38_0
  - dask-ml=2024.4.4=py38h06a4308_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distributed=2023.4.1=py38h06a4308_1
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - et_xmlfile=1.1.0=py38h06a4308_0
  - exceptiongroup=1.2.0=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h6a678d5_0
  - fasteners=0.16.3=pyhd3eb1b0_0
  - filelock=3.13.1=py38h06a4308_0
  - flask=3.0.3=py38h06a4308_0
  - flask-compress=1.13=py38h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h55d465d_3
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.51.0=py38h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.4.0=py38h5eee18b_0
  - fsspec=2024.6.1=py38h06a4308_0
  - gdk-pixbuf=2.42.10=h5eee18b_1
  - giflib=5.2.2=h5eee18b_0
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py38h06a4308_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gobject-introspection=1.78.1=py38h42194e9_1
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h78213b7_2
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=hb67d8dd_3
  - harfbuzz=4.3.0=hf52aaf7_2
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py38h06a4308_0
  - importlib-metadata=7.0.1=py38h06a4308_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py38h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py38h06a4308_0
  - ipython=8.12.2=py38h06a4308_0
  - itsdangerous=2.2.0=py38h06a4308_0
  - jedi=0.19.1=py38h06a4308_0
  - jinja2=3.1.4=py38h06a4308_0
  - joblib=1.4.2=py38h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jsonschema=4.23.0=py38h06a4308_0
  - jupyter-server-proxy=4.1.2=py38h06a4308_0
  - jupyter_client=8.6.0=py38h06a4308_0
  - jupyter_core=5.7.2=py38h06a4308_0
  - jupyter_events=0.10.0=py38h06a4308_0
  - jupyter_server=2.14.1=py38h06a4308_0
  - jupyter_server_terminals=0.4.4=py38h06a4308_1
  - jupyterlab-dash=0.1.0a2=py_0
  - jupyterlab_pygments=0.2.2=py38h06a4308_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.11.1=hc9e6f67_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgd=2.3.3=h695aa2c_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - librsvg=2.56.3=h056759b_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=hffd6297_1
  - libtool=2.4.6=h6a678d5_1009
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxgboost=2.1.1=h6a678d5_0
  - libxml2=2.13.5=hfdd30dd_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.41.0=py38he621ea3_0
  - locket=1.0.0=py38h06a4308_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py38h5eee18b_0
  - matplotlib-base=3.7.1=py38h417a72b_1
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mistune=2.0.4=py38h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py38h06a4308_0
  - msgpack-python=1.0.3=py38hd09550d_0
  - multidict=6.0.4=py38h5eee18b_0
  - multipledispatch=0.6.0=py38_0
  - mypy_extensions=1.0.0=py38h06a4308_0
  - nbclient=0.8.0=py38h06a4308_0
  - nbconvert=7.16.4=py38h06a4308_0
  - nbformat=5.10.4=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py38h06a4308_0
  - networkx=2.6.3=pyhd8ed1ab_1
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numba=0.58.1=py38h6a678d5_0
  - numcodecs=0.12.1=py38h2c38b39_0
  - numexpr=2.8.4=py38hc78ab66_1
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - obonet=0.2.3=py_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openai=0.27.10=pyhd8ed1ab_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openpyxl=3.1.5=py38h5eee18b_0
  - openssl=3.0.16=h5eee18b_0
  - overrides=7.4.0=py38h06a4308_0
  - packaging=24.1=py38h06a4308_0
  - pandas=2.0.3=py38h1128e8f_0
  - pandas-stubs=1.2.0.62=py38h578d9bd_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.50.7=h05da053_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.1=py38h06a4308_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.4.0=py38h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pkgutil-resolve-name=1.3.10=py38h06a4308_1
  - platformdirs=3.10.0=py38h06a4308_0
  - plotly=5.24.1=py_0
  - pluggy=1.0.0=py38h06a4308_1
  - pooch=1.7.0=py38h06a4308_0
  - poppler=24.09.0=hcf11d46_1
  - poppler-data=0.4.11=h06a4308_1
  - prettytable=0.7.2=py_3
  - prometheus_client=0.14.1=py38h06a4308_0
  - prompt-toolkit=3.0.43=py38h06a4308_0
  - protobuf=4.25.3=py38h12ddb61_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=2.1.1=cpu_pyhb442362_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py38h06a4308_1
  - pygraphviz=1.9=py38h86b1bdd_0
  - pyparsing=3.1.2=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - pytest=7.4.4=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python-json-logger=2.0.7=py38h06a4308_0
  - python-lmdb=1.4.1=py38h6a678d5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=2.5.0.dev20240731=py3.8_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py38h06a4308_0
  - pyyaml=6.0.2=py38h5eee18b_0
  - pyzmq=25.1.2=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - rechunker=0.5.2=pyhd8ed1ab_1
  - requests=2.32.3=py38h06a4308_0
  - rfc3339-validator=0.1.4=py38h06a4308_0
  - rfc3986-validator=0.1.1=py38h06a4308_0
  - scikit-learn=1.3.0=py38h1128e8f_1
  - scipy=1.10.1=py38hf6e8229_1
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - send2trash=1.8.2=py38h06a4308_0
  - sentry-sdk=1.9.10=pyhd8ed1ab_0
  - setproctitle=1.2.2=py38h27cfd23_1004
  - setuptools=75.1.0=py38h06a4308_0
  - sgkit=0.8.0=pyhd8ed1ab_0
  - simpervisor=1.0.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - sniffio=1.3.0=py38h06a4308_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.0=py38ha9d4c09_0
  - sympy=1.13.3=py38h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=9.0.0=py38h06a4308_0
  - terminado=0.17.1=py38h06a4308_0
  - threadpoolctl=3.5.0=py38h2f386ee_0
  - tinycss2=1.2.1=py38h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py38h06a4308_0
  - toolz=0.12.0=py38h06a4308_0
  - torchtriton=3.0.0+dedb7bdf33=py38
  - tornado=6.4.1=py38h5eee18b_0
  - tqdm=4.67.0=pyhd8ed1ab_0
  - traitlets=5.14.3=py38h06a4308_0
  - typing-extensions=4.11.0=py38h06a4308_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - unicodedata2=15.1.0=py38h5eee18b_0
  - urllib3=2.2.3=py38h06a4308_0
  - wandb=0.16.6=pyhd8ed1ab_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - websocket-client=1.8.0=py38h06a4308_0
  - wheel=0.44.0=py38h06a4308_0
  - xarray=2022.11.0=py38h06a4308_0
  - xgboost=2.1.1=cpu_pyhb8f9a19_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.11.0=py38h5eee18b_0
  - zarr=2.13.3=py38h06a4308_0
  - zeromq=4.3.5=h6a678d5_0
  - zict=3.0.0=py38h06a4308_0
  - zipp=3.20.2=py38h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - ansi2html==1.9.2
      - attrs==24.3.0
      - blinker==1.8.2
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - fastjsonschema==2.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-dash==0.4.2
      - kaleido==0.2.1
      - referencing==0.35.1
      - retrying==1.3.4
      - rpds-py==0.20.1
      - werkzeug==3.0.6
prefix: /cellar/users/i5lee/miniconda3/envs/G2PT_github_unit_test
